/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionCopilotRouteImport } from './routes/action-copilot'
import { Route as FinancialClarityRouteImport } from './routes/financial-clarity'
import { Route as GrowthBlockerRouteImport } from './routes/growth-blocker'
import { Route as RestockRouteImport } from './routes/restock'
import { Route as WhatIfRouteImport } from './routes/what-if'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionCopilotRoute = ActionCopilotRouteImport.update({
  id: '/action-copilot',
  path: '/action-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialClarityRoute = FinancialClarityRouteImport.update({
  id: '/financial-clarity',
  path: '/financial-clarity',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthBlockerRoute = GrowthBlockerRouteImport.update({
  id: '/growth-blocker',
  path: '/growth-blocker',
  getParentRoute: () => rootRouteImport,
} as any)
const RestockRoute = RestockRouteImport.update({
  id: '/restock',
  path: '/restock',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-copilot': typeof ActionCopilotRoute
  '/financial-clarity': typeof FinancialClarityRoute
  '/growth-blocker': typeof GrowthBlockerRoute
  '/restock': typeof RestockRoute
  '/what-if': typeof WhatIfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-copilot': typeof ActionCopilotRoute
  '/financial-clarity': typeof FinancialClarityRoute
  '/growth-blocker': typeof GrowthBlockerRoute
  '/restock': typeof RestockRoute
  '/what-if': typeof WhatIfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-copilot': typeof ActionCopilotRoute
  '/financial-clarity': typeof FinancialClarityRoute
  '/growth-blocker': typeof GrowthBlockerRoute
  '/restock': typeof RestockRoute
  '/what-if': typeof WhatIfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-copilot'
    | '/financial-clarity'
    | '/growth-blocker'
    | '/restock'
    | '/what-if'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-copilot'
    | '/financial-clarity'
    | '/growth-blocker'
    | '/restock'
    | '/what-if'
  id:
    | '__root__'
    | '/'
    | '/action-copilot'
    | '/financial-clarity'
    | '/growth-blocker'
    | '/restock'
    | '/what-if'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionCopilotRoute: typeof ActionCopilotRoute
  FinancialClarityRoute: typeof FinancialClarityRoute
  GrowthBlockerRoute: typeof GrowthBlockerRoute
  RestockRoute: typeof RestockRoute
  WhatIfRoute: typeof WhatIfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-copilot': {
      id: '/action-copilot'
      path: '/action-copilot'
      fullPath: '/action-copilot'
      preLoaderRoute: typeof ActionCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-clarity': {
      id: '/financial-clarity'
      path: '/financial-clarity'
      fullPath: '/financial-clarity'
      preLoaderRoute: typeof FinancialClarityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-blocker': {
      id: '/growth-blocker'
      path: '/growth-blocker'
      fullPath: '/growth-blocker'
      preLoaderRoute: typeof GrowthBlockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restock': {
      id: '/restock'
      path: '/restock'
      fullPath: '/restock'
      preLoaderRoute: typeof RestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionCopilotRoute: ActionCopilotRoute,
  FinancialClarityRoute: FinancialClarityRoute,
  GrowthBlockerRoute: GrowthBlockerRoute,
  RestockRoute: RestockRoute,
  WhatIfRoute: WhatIfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
